### ISSUE TITLE
Will the dataset be released alongside the code?

### ISSUE THREAD

**Issue by TrevorPatrick0918** [elijahcole/sinr#1]
Hi, 

Thanks for your great work! 

I am wondering will the dataset be released alongside the code? Or if there is some other way for us to obtain the dataset from https://www.inaturalist.org/?

**Comment by elijahcole** [comment]
Thank you for the kind words! Yes, we are planning to release the data (and/or instructions for reproducing the data from public sources) as well. Details will follow soon!

**Comment by elijahcole** [comment]
@TrevorPatrick0918 The data and code are available now!
