### ISSUE TITLE
InvalidParameterError in viz_ica.py

### ISSUE THREAD

**Issue by mrtnlowry** [elijahcole/sinr#10]
See line 69:
dsf = decomposition.FastICA(n_components=num_ds_dims, random_state=seed, whiten=True, max_iter=1000)

Produces this error:
sklearn.utils._param_validation.InvalidParameterError: The 'whiten' parameter of FastICA must be a str among {'arbitrary-variance', 'unit-variance'} or a bool among {False}. Got True instead.

Replace with:
dsf = decomposition.FastICA(n_components=num_ds_dims, random_state=seed, whiten='unit-variance', max_iter=1000)

**Comment by macaodha** [comment]
Thanks for flagging this. We had tested with an older version of sklearn. Should be fixed with the latest commit.
