### ISSUE TITLE
Minor Bug Report & Fix for Web App

### ISSUE THREAD

**Issue by Shiran-Yuan** [elijahcole/sinr#11]
Hi it's me again :-) 

When I was using the web app it complained for `return op_html, fig, gr.Number.update(value=eval_params['taxa_id'])` that `AttributeError: type object 'Number' has no attribute 'update'`. 

I changed the line to `return op_html, fig, eval_params['taxa_id']` and it seems to work fine.

**Comment by macaodha** [comment]
Hi there,  

I added the change - thanks!

**Comment by elijahcole** [comment]
Closing since the issue has been fixed - please reopen if needed!
