### ISSUE TITLE
Environmental data mirrors are down

### ISSUE THREAD

**Issue by reidsteele2** [elijahcole/sinr#12]
Mirrors in the data section for environmental data are currently down:

`curl -L https://biogeo.ucdavis.edu/data/worldclim/v2.1/base/wc2.1_5m_bio.zip --output wc2.1_5m_bio.zip
curl -L https://biogeo.ucdavis.edu/data/worldclim/v2.1/base/wc2.1_5m_elev.zip --output wc2.1_5m_elev.zip`

Have been down about a week. Is there anywhere else to get them from?

**Comment by Chris-lange** [comment]
Hi reidsteele2,

Thanks for bringing that up! I have updated the data/README.md to include corrected links. I think UC Davis changed where they store their files.

If this happens again, the below site has links to download the data ('Bioclimatic variables' and 'Elevation' at 5 minute resolution):

https://www.worldclim.org/data/worldclim21.html
