### ISSUE TITLE
Proposal for Improvements

### ISSUE THREAD

**Issue by Shiran-Yuan** [elijahcole/sinr#3]
Hi! Thanks again for the work, it really helped me a lot. However, I did notice some small inconveniences with the codebase, so I thought the codebase could be improved via fixing those.

1. `np.int` was used for 4 times in `datasets.py`. It was deprecated long ago and should be replaced with `np.int32`.
2. If `experiments/demo` exists the program would fail to run due to `FileExists`. It should be autodeleted when the code is ran, or saved under a name that includes the local time.
3. Training an epoch takes around 30 minutes on my server but there's no display of progress. I recommend adding a tqdm progress bar.

I thought it would be helpful to introduce those into the codebase. If the authors agree I could open a pull request with the fixes implemented ;-)

**Comment by macaodha** [comment]
Hi @Shiran-Yuan thanks for flagging these!

As a note to myself, another minor warning that would be nice for us to fix is the following which pops up sometimes.  

models.py:60: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3277.)
  return torch.matmul(x, self.class_emb.weight[class_of_interest, :].T)

Would need to be careful with this to make sure the fix behaves as intended in all cases.

**Comment by macaodha** [comment]
Hi again @Shiran-Yuan 

Thanks for your pull request! I've incorporated some of your changes into an updated commit. 

Note I didn't address 2 and 3, as 2 is helpful to prevent people from overwriting old experiments and 3 is not needed as we already have a simple progress logger [here](https://github.com/elijahcole/sinr/blob/main/train.py#L50). Note sure why you are not seeing a progress update during training as I see one. You can set the log frequency [here](https://github.com/elijahcole/sinr/blob/main/setup.py#L59). 

The latest update, also speeds up the evaluation which can be slow at the end of training.
