### ISSUE TITLE
Raw Coordinates without Trigonometric Encoding?

### ISSUE THREAD

**Issue by Shiran-Yuan** [elijahcole/sinr#7]
Hi! I'm trying to build a similar network, but I would like to experiment with potential encodings besides the regular sin-cos version. It is of course possible to generate the raw data from the provided sin-cos version, but I'm a bit worried about accuracy issues. Can you please kindly open-source the raw data without the sin-cos encoding? Thank you!

**Comment by macaodha** [comment]
Hi @Shiran-Yuan 

Thanks for your interest in our project!  

The data provided is actually the raw coordinate values, i.e. the latitude and longitude for each observation. Our networks do indeed perform a cos and sin transformation, but that happens in the code, not from the input data:  
https://github.com/elijahcole/sinr/blob/main/utils.py#L16

**Comment by Shiran-Yuan** [comment]
Oh I see. Thanks!
