### ISSUE TITLE
Faulty libdeflate package

### ISSUE THREAD

**Issue by mrtnlowry** [elijahcole/sinr#8]
Anaconda automatically installs libdeflate-1.17. Unfortunately this fails with a LIBDEFLATE_INSUFFICIENT_SPACE error when running format_env_feats.py.  Downgrading to libdeflate-1.8 fixes this.

**Comment by mrtnlowry** [comment]
Update: It's not the imagecodecs package that's faulty, it's libdeflate-1.17; replaced with libdeflate-1.8

**Comment by macaodha** [comment]
Again - thanks :-). 

I've added another package to the requirements that fixes this.
