### ISSUE TITLE
ValueError in viz_map.py

### ISSUE THREAD

**Issue by mrtnlowry** [elijahcole/sinr#9]
Line 76 of the code produces a "shape mismatch" message. This appears to caused by preds.shape being too large (499385,256) to be pasted into op_im (shape: (499385,)).  Which slice of preds is the correct one to use?

**Comment by macaodha** [comment]
Hi there.  

Can you confirm that you have not modified this line:  
https://github.com/elijahcole/sinr/blob/df676beece3234382d9623530d6bfef5ee9c699a/viz_map.py#L65  

``preds`` should have the same number of entries as rows in ``locs_enc`` and have a single value for each entry.

**Comment by mrtnlowry** [comment]
Hello,

I didn't modify any of the code. After replacing the faulty libdeflate
package I opened a terminal from Anaconda and ran viz_map code in the pdb
debugger. Here's the output - with irrelevant lines removed.

(GeoModel) D:\Data\PyCharm\sinr-main>python -m pdb viz_map.py
--taxa_id=870009
> d:\data\pycharm\sinr-main\viz_map.py(1)<module>()
-> """
(Pdb) n
> d:\data\pycharm\sinr-main\viz_map.py(6)<module>()
-> import torch

....

-> main(eval_params)
(Pdb) s
--Call--
> d:\data\pycharm\sinr-main\viz_map.py(18)main()
-> def main(eval_params):
....

Loading taxa: 870009
...

> d:\data\pycharm\sinr-main\viz_map.py(61)main()
-> locs_enc = enc.encode(locs).to(eval_params['device'])
(Pdb) n
> d:\data\pycharm\sinr-main\viz_map.py(64)main()
-> with torch.no_grad():
(Pdb) locs_enc.shape
torch.Size([499385, 4])

(Pdb) n
> d:\data\pycharm\sinr-main\viz_map.py(65)main()
-> preds = model(locs_enc, return_feats=False,
class_of_interest=class_of_interest).cpu().numpy()
(Pdb) n
> d:\data\pycharm\sinr-main\viz_map.py(68)main()
-> if eval_params['threshold'] > 0:
(Pdb) preds.shape
(499385, 256)
(Pdb) n
> d:\data\pycharm\sinr-main\viz_map.py(74)main()
-> if not eval_params['disable_ocean_mask']:
(Pdb) n
> d:\data\pycharm\sinr-main\viz_map.py(75)main()
-> op_im = np.ones((mask.shape[0] * mask.shape[1])) * np.nan  # set to NaN
(Pdb) n
> d:\data\pycharm\sinr-main\viz_map.py(76)main()
-> op_im[mask_inds] = preds
(Pdb) n
ValueError: shape mismatch: value array of shape (499385,256) could not be
broadcast to indexing result of shape (499385,)
(Pdb) q


Cheers,
Martin

**Comment by mrtnlowry** [comment]
The code here 

https://github.com/macaodha/geo_prior/blob/b0c761712a0aeced56eba86dd19eda657fbe895a/geo_prior/models.py#L58

uses "torch.matmul(x, ...)" rather than the equivalent line in this package which uses "x * ...". Is that significant?

**Comment by macaodha** [comment]
Thanks for flagging this. Yes, it was an issue with how "*" is treated in the version of torch specified in the requirements. Should be fixed with the latest commit.
